services:
  postgres:
    image: postgres:17-alpine
    container_name: nextapp_postgres
    restart: unless-stopped
    ports:
      - "5033:5432"
    environment:
      POSTGRES_USER: nextapp
      POSTGRES_PASSWORD: nextapp_secret
      POSTGRES_DB: nextapp_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
